"""Development-only hybrid communication runtime for Urusilla 0.1.0.

This package does not promote a new protocol version or claim general token
efficiency.  Unknown, ambiguous, unsupported, or unproven inputs retain a raw
or canonical-JSON fallback.
"""

from .canonical import HybridRuntimeError, JsonValidationError, canonical_json, strict_json_loads
from .errors import (
    ActionStateError,
    CapsuleError,
    ReceiverError,
    RoutingError,
    SenderError,
    SurfaceError,
    TaskContextError,
)
from .integrity import current_runtime_sha256
from .fidelity import FidelityVerification, FidelityVerificationInput
from .receiver import (
    DirectReceiverRequest,
    ReceiverExecution,
    ReceiverModelAdapter,
    ReceiverModelReply,
    SurfaceShadowExecution,
    build_action_state_request,
    build_json_fallback_payload,
    build_json_request,
    build_raw_request,
    build_routine_request,
    build_silence_request,
    build_shadow_surface_action_state_request,
    consume_direct_action_state,
    execute_receiver,
    execute_shadow_surface_request,
)
from .records import (
    ACTION_STATE_FORMAT,
    Capsule,
    PublicActionState,
    load_capsule,
    source_text_sha256,
    validate_action_state,
    wrap_as_quarantined_urusilla_message,
)
from .router import (
    CostForecast,
    CostLedger,
    LocalArtifactVerification,
    ReceiverCapabilities,
    RouteCandidate,
    RouteDecision,
    RouterPolicy,
    RoutineInvocation,
    SilenceProof,
    UtilityEvidence,
    action_state_preflight,
    plan_route,
    should_attempt_action_state,
)
from .runtime import (
    HybridExecution,
    LocalOutputValidation,
    OutputValidationInput,
    PreparedMessage,
    execute_prepared_message,
    prepare_message,
)
from .task_context import (
    PublicTaskContext,
    TASK_CONTEXT_FORMAT,
    validate_state_against_task_context,
    validate_task_context,
)
from .sender import (
    CapsuleContextBinding,
    CompileOutcome,
    ModelReply,
    SenderContextVerification,
    SenderPrompt,
    StructuredCompiler,
    build_sender_prompt,
    compile_natural_language,
    not_attempted,
    parse_sender_output,
)
from .surface import (
    ActiveSurface,
    EVOLVING_SURFACE_CAPSULE_SHA256,
    RetainedSurface,
    SurfaceActivationEvidence,
    SurfaceAliasTable,
    SurfaceArtifactVerification,
    SurfaceCarrier,
    SurfaceEvolutionDecision,
    SurfaceScope,
    SurfaceTrial,
    SurfaceTrialPlan,
    activate_surface,
    allowed_semantic_refs,
    decide_surface_evolution,
    decode_surface_state,
    encode_surface_state,
    optimize_alias_table,
)


__all__ = [
    "ACTION_STATE_FORMAT",
    "ActiveSurface",
    "ActionStateError",
    "TASK_CONTEXT_FORMAT",
    "Capsule",
    "CapsuleError",
    "CapsuleContextBinding",
    "CompileOutcome",
    "CostForecast",
    "CostLedger",
    "FidelityVerification",
    "FidelityVerificationInput",
    "LocalArtifactVerification",
    "LocalOutputValidation",
    "OutputValidationInput",
    "DirectReceiverRequest",
    "EVOLVING_SURFACE_CAPSULE_SHA256",
    "ReceiverExecution",
    "ReceiverModelAdapter",
    "ReceiverModelReply",
    "HybridRuntimeError",
    "HybridExecution",
    "JsonValidationError",
    "ModelReply",
    "PreparedMessage",
    "PublicActionState",
    "PublicTaskContext",
    "ReceiverCapabilities",
    "ReceiverError",
    "RetainedSurface",
    "RouteCandidate",
    "RouteDecision",
    "RouterPolicy",
    "RoutingError",
    "RoutineInvocation",
    "SenderError",
    "SenderContextVerification",
    "SenderPrompt",
    "SilenceProof",
    "StructuredCompiler",
    "SurfaceActivationEvidence",
    "SurfaceAliasTable",
    "SurfaceArtifactVerification",
    "SurfaceCarrier",
    "SurfaceError",
    "SurfaceEvolutionDecision",
    "SurfaceScope",
    "SurfaceShadowExecution",
    "SurfaceTrial",
    "SurfaceTrialPlan",
    "TaskContextError",
    "UtilityEvidence",
    "action_state_preflight",
    "activate_surface",
    "allowed_semantic_refs",
    "build_action_state_request",
    "build_json_fallback_payload",
    "build_json_request",
    "build_raw_request",
    "build_routine_request",
    "build_sender_prompt",
    "build_silence_request",
    "build_shadow_surface_action_state_request",
    "canonical_json",
    "compile_natural_language",
    "consume_direct_action_state",
    "current_runtime_sha256",
    "decide_surface_evolution",
    "decode_surface_state",
    "encode_surface_state",
    "execute_prepared_message",
    "execute_receiver",
    "execute_shadow_surface_request",
    "load_capsule",
    "not_attempted",
    "optimize_alias_table",
    "parse_sender_output",
    "plan_route",
    "prepare_message",
    "should_attempt_action_state",
    "source_text_sha256",
    "strict_json_loads",
    "validate_action_state",
    "validate_state_against_task_context",
    "validate_task_context",
    "wrap_as_quarantined_urusilla_message",
]
